/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playground;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author zabdu
 */
public class frm_utama extends javax.swing.JFrame {
    koneksi dbsetting;
    String driver,database,user,pass,nama,alamat,notelp;
    Integer umur;
    /**
     * Creates new form frmutama
     */
    public frm_utama() {
        initComponents();
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pn_content = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_home = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel_transaksi = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btn_tambah = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        cbx_olimesin = new javax.swing.JCheckBox();
        cbx_lager = new javax.swing.JCheckBox();
        cbx_fanbelt = new javax.swing.JCheckBox();
        cbx_kampasrem = new javax.swing.JCheckBox();
        spn_olimesin = new javax.swing.JSpinner();
        spn_fanbelt = new javax.swing.JSpinner();
        spn_lager = new javax.swing.JSpinner();
        spn_kampasrem = new javax.swing.JSpinner();
        cbx_shockbreaker = new javax.swing.JCheckBox();
        cbx_busi = new javax.swing.JCheckBox();
        cbx_platinacondesor = new javax.swing.JCheckBox();
        cbx_platkopling = new javax.swing.JCheckBox();
        spn_shockbreaker = new javax.swing.JSpinner();
        spn_platinacondesor = new javax.swing.JSpinner();
        spn_busi = new javax.swing.JSpinner();
        spn_platkopling = new javax.swing.JSpinner();
        cbx_enginemounting = new javax.swing.JCheckBox();
        cbx_olirem = new javax.swing.JCheckBox();
        cbx_radiator = new javax.swing.JCheckBox();
        cbx_airradiatorcoolant = new javax.swing.JCheckBox();
        spn_enginemounting = new javax.swing.JSpinner();
        spn_radiator = new javax.swing.JSpinner();
        spn_olirem = new javax.swing.JSpinner();
        spn_airradiatorcoolant = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        panel_histori = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_navbar.setBackground(new java.awt.Color(0, 0, 102));
        pn_navbar.setForeground(new java.awt.Color(0, 0, 102));
        pn_navbar.setPreferredSize(new java.awt.Dimension(622, 50));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bengkel Cissy");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\zabdu\\Documents\\MataKuliah\\Semester_2\\Pemrograman Berorientasi Objek\\TugasBesar\\TUBES-PBO\\Playground\\lib\\Gambar\\Logo2.png")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_sidebar.setPreferredSize(new java.awt.Dimension(150, 402));

        jButton1.setText("Home");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Input Barang");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Transaksi");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("Welcome");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("PROFILE");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nama");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Alamat");
        jLabel11.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Umur");
        jLabel12.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("No Telp");
        jLabel13.setToolTipText("");

        txt_alamat_profile.setColumns(10);
        txt_alamat_profile.setRows(1);
        jScrollPane1.setViewportView(txt_alamat_profile);

        btn_update_profile.setText("Update");

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_update_profile)
                    .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(profileLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(29, 29, 29)
                            .addComponent(txt_nama_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel9)
                        .addGroup(profileLayout.createSequentialGroup()
                            .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_umur_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_notelp_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_nama_profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_umur_profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_notelp_profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btn_update_profile)
                .addGap(73, 73, 73))
        );

        jTabbedPane1.addTab("Profile", profile);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setText("Welcome Home");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel2)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel2)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", panel_home);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_tambah.setBackground(new java.awt.Color(204, 255, 204));
        btn_tambah.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        jPanel7.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 80, 30));

        btn_reset.setBackground(new java.awt.Color(255, 204, 204));
        btn_reset.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });
        jPanel7.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 80, 30));

        cbx_olimesin.setBackground(new java.awt.Color(204, 204, 255));
        cbx_olimesin.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_olimesin.setText("Oli Mesin");
        cbx_olimesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_olimesinActionPerformed(evt);
            }
        });
        jPanel7.add(cbx_olimesin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        cbx_lager.setBackground(new java.awt.Color(204, 204, 255));
        cbx_lager.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_lager.setText("Lager");
        jPanel7.add(cbx_lager, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, -1));

        cbx_fanbelt.setBackground(new java.awt.Color(204, 204, 255));
        cbx_fanbelt.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_fanbelt.setText("Fan Belt");
        jPanel7.add(cbx_fanbelt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, -1));

        cbx_kampasrem.setBackground(new java.awt.Color(204, 204, 255));
        cbx_kampasrem.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_kampasrem.setText("Kampas Rem");
        jPanel7.add(cbx_kampasrem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, -1));

        spn_olimesin.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_olimesin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 50, -1));

        spn_fanbelt.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_fanbelt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 50, -1));

        spn_lager.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_lager, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 50, -1));

        spn_kampasrem.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_kampasrem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 50, -1));

        cbx_shockbreaker.setBackground(new java.awt.Color(204, 204, 255));
        cbx_shockbreaker.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_shockbreaker.setText("ShockBreaker");
        cbx_shockbreaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_shockbreakerActionPerformed(evt);
            }
        });
        jPanel7.add(cbx_shockbreaker, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, -1));

        cbx_busi.setBackground(new java.awt.Color(204, 204, 255));
        cbx_busi.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_busi.setText("Busi");
        jPanel7.add(cbx_busi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 120, -1));

        cbx_platinacondesor.setBackground(new java.awt.Color(204, 204, 255));
        cbx_platinacondesor.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_platinacondesor.setText("Platina Condesor");
        jPanel7.add(cbx_platinacondesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 120, -1));

        cbx_platkopling.setBackground(new java.awt.Color(204, 204, 255));
        cbx_platkopling.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_platkopling.setText("Plat Kopling");
        jPanel7.add(cbx_platkopling, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 120, -1));

        spn_shockbreaker.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_shockbreaker, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 50, -1));

        spn_platinacondesor.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_platinacondesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, -1));

        spn_busi.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_busi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 50, -1));

        spn_platkopling.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_platkopling, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 50, -1));

        cbx_enginemounting.setBackground(new java.awt.Color(204, 204, 255));
        cbx_enginemounting.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_enginemounting.setText("Engine Mounting");
        cbx_enginemounting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_enginemountingActionPerformed(evt);
            }
        });
        jPanel7.add(cbx_enginemounting, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 120, -1));

        cbx_olirem.setBackground(new java.awt.Color(204, 204, 255));
        cbx_olirem.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_olirem.setText("Oli Rem");
        jPanel7.add(cbx_olirem, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 120, -1));

        cbx_radiator.setBackground(new java.awt.Color(204, 204, 255));
        cbx_radiator.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_radiator.setText("Radiator");
        jPanel7.add(cbx_radiator, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 120, -1));

        cbx_airradiatorcoolant.setBackground(new java.awt.Color(204, 204, 255));
        cbx_airradiatorcoolant.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        cbx_airradiatorcoolant.setText("AIR RADIATOR COOLANT ");
        jPanel7.add(cbx_airradiatorcoolant, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, -1));

        spn_enginemounting.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_enginemounting, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 50, -1));

        spn_radiator.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_radiator, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 50, -1));

        spn_olirem.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_olirem, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 50, -1));

        spn_airradiatorcoolant.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jPanel7.add(spn_airradiatorcoolant, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 50, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Penginputan Barang");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        javax.swing.GroupLayout panel_transaksiLayout = new javax.swing.GroupLayout(panel_transaksi);
        panel_transaksi.setLayout(panel_transaksiLayout);
        panel_transaksiLayout.setHorizontalGroup(
            panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_transaksiLayout.setVerticalGroup(
            panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", panel_transaksi);

        jLabel5.setText("3");

        javax.swing.GroupLayout panel_historiLayout = new javax.swing.GroupLayout(panel_histori);
        panel_histori.setLayout(panel_historiLayout);
        panel_historiLayout.setHorizontalGroup(
            panel_historiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_historiLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        panel_historiLayout.setVerticalGroup(
            panel_historiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_historiLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel5)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", panel_histori);

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_contentLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_contentLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabel8.setText(nama);
        txt_nama_profile.setText(nama);
        txt_umur_profile.setText(umur.toString());
        txt_alamat_profile.setText(alamat);
        txt_notelp_profile.setText(notelp);
    }//GEN-LAST:event_formWindowOpened
    
    
    
    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            Statement stt = kon.createStatement();
            if (cbx_olimesin.isSelected()) {
                int angka_real = (int) spn_olimesin.getValue();
                String SQL = "SELECT JUMLAH from barang WHERE id='1'";
                ResultSet rs = stt.executeQuery(SQL);
                while(rs.next()){
                    int jml = rs.getInt("jumlah");
                    angka_real = jml + angka_real;
                }
                String SQL1 = "UPDATE `barang` SET `JUMLAH` = '"+angka_real+"' WHERE `barang`.`id` = '1';";
                stt.executeUpdate(SQL1);
            }
            if (cbx_fanbelt.isSelected()) {
                int angka_real = (int) spn_fanbelt.getValue();
                String SQL = "SELECT jumlah from barang WHERE id='2'";
                ResultSet rs = stt.executeQuery(SQL);
                while(rs.next()){
                    int jml = rs.getInt("jumlah");
                    angka_real = jml + angka_real;
                }
                String SQL1 = "UPDATE `barang` SET `jumlah` = '"+angka_real+"' WHERE `barang`.`id` = '2';";
                stt.executeUpdate(SQL1);
            }
            kon.close();
            stt.close();
            JOptionPane.showMessageDialog(null, "Berhasil Dimasukan");

        } catch (Exception ex) {
            System.err.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(),"ERROR",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        frm_login login = new frm_login();
        login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void cbx_shockbreakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_shockbreakerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_shockbreakerActionPerformed

    private void cbx_enginemountingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_enginemountingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_enginemountingActionPerformed

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        // TODO add your handling code here:
        spn_olimesin.setValue(0);
        spn_fanbelt.setValue(0);
        spn_lager.setValue(0);
        spn_kampasrem.setValue(0);
        spn_shockbreaker.setValue(0);
        spn_platinacondesor.setValue(0);
        spn_busi.setValue(0);
        spn_platkopling.setValue(0);
        spn_enginemounting.setValue(0);
        spn_radiator.setValue(0);
        spn_olirem.setValue(0);
        spn_airradiatorcoolant.setValue(0);
    }//GEN-LAST:event_btn_resetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JCheckBox cbx_airradiatorcoolant;
    private javax.swing.JCheckBox cbx_busi;
    private javax.swing.JCheckBox cbx_enginemounting;
    private javax.swing.JCheckBox cbx_fanbelt;
    private javax.swing.JCheckBox cbx_kampasrem;
    private javax.swing.JCheckBox cbx_lager;
    private javax.swing.JCheckBox cbx_olimesin;
    private javax.swing.JCheckBox cbx_olirem;
    private javax.swing.JCheckBox cbx_platinacondesor;
    private javax.swing.JCheckBox cbx_platkopling;
    private javax.swing.JCheckBox cbx_radiator;
    private javax.swing.JCheckBox cbx_shockbreaker;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel_histori;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_transaksi;
    private javax.swing.JSpinner spn_airradiatorcoolant;
    private javax.swing.JSpinner spn_busi;
    private javax.swing.JSpinner spn_enginemounting;
    private javax.swing.JSpinner spn_fanbelt;
    private javax.swing.JSpinner spn_kampasrem;
    private javax.swing.JSpinner spn_lager;
    private javax.swing.JSpinner spn_olimesin;
    private javax.swing.JSpinner spn_olirem;
    private javax.swing.JSpinner spn_platinacondesor;
    private javax.swing.JSpinner spn_platkopling;
    private javax.swing.JSpinner spn_radiator;
    private javax.swing.JSpinner spn_shockbreaker;
    // End of variables declaration//GEN-END:variables
}
